name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: dotnet restore
      run: cd ./src/ && dotnet restore
    - name: dotnet build
      run: cd ./src/ && dotnet build --configuration Release --no-restore
    - name: dotnet test
      run: cd ./src/Tests/ && dotnet test --no-restore --verbosity normal
    - name: dotnet pack
      run: cd ./src/Bootstrapper/ && dotnet pack
